
const SelectionOptions = [
    {
        "Category":"Body",
        "FolderPath":"9696_img/Body",
        "Options": [
            {
                "ImageLabel":"Body",
                "ImagePath":"9696_img/Body/Body_1.png"
            }
        ]
    },
    {
        "Category":"Eyes",
        "FolderPath":"9696_img/Eyes",
        "Options": [
            {
                "ImageLabel":"Eyes1",
                "ImagePath":"9696_img/Eyes/Eyes_1.png"
            },
            {
                "ImageLabel":"Eyes2",
                "ImagePath":"9696_img/Eyes/Eyes_2.png"
            },
            {
                "ImageLabel":"Eyes3",
                "ImagePath":"9696_img/Eyes/Eyes_3.png"
            },
            {
                "ImageLabel":"Eyes4",
                "ImagePath":"9696_img/Eyes/Eyes_4.png"
            },
            {
                "ImageLabel":"Eyes5",
                "ImagePath":"9696_img/Eyes/Eyes_5.png"
            },
            {
                "ImageLabel":"Eyes6",
                "ImagePath":"9696_img/Eyes/Eyes_6.png"
            }
        ]
    },
    {
        "Category":"Mouth",
        "FolderPath":"9696_img/Mouth",
        "Options": [
            {
                "ImageLabel":"Mouth1",
                "ImagePath":"9696_img/Mouth/Mouth_1.png"
            },
            {
                "ImageLabel":"Mouth2",
                "ImagePath":"9696_img/Mouth/Mouth_2.png"
            },
            {
                "ImageLabel":"Mouth3",
                "ImagePath":"9696_img/Mouth/Mouth_3.png"
            },
            {
                "ImageLabel":"Mouth4",
                "ImagePath":"9696_img/Mouth/Mouth_4.png"
            },
            {
                "ImageLabel":"Mouth5",
                "ImagePath":"9696_img/Mouth/Mouth_5.png"
            },
            {
                "ImageLabel":"Mouth6",
                "ImagePath":"9696_img/Mouth/Mouth_6.png"
            },
            {
                "ImageLabel":"Mouth7",
                "ImagePath":"9696_img/Mouth/Mouth_7.png"
            },
            {
                "ImageLabel":"Mouth8",
                "ImagePath":"9696_img/Mouth/Mouth_8.png"
            },
            {
                "ImageLabel":"Mouth9",
                "ImagePath":"9696_img/Mouth/Mouth_9.png"
            },
            {
                "ImageLabel":"Mouth10",
                "ImagePath":"9696_img/Mouth/Mouth_10.png"
            },
            {
                "ImageLabel":"Mouth11",
                "ImagePath":"9696_img/Mouth/Mouth_11.png"
            },
            {
                "ImageLabel":"Mouth12",
                "ImagePath":"9696_img/Mouth/Mouth_12.png"
            },
            {
                "ImageLabel":"Mouth13",
                "ImagePath":"9696_img/Mouth/Mouth_13.png"
            }
        ]
    },
    {
        "Category":"Weapon",
        "FolderPath":"9696_img/Weapon",
        "Options": [
            {
                "ImageLabel":"Weapon",
                "ImagePath":"9696_img/Weapon/Weapon_1.png"
            }
        ]
    },
]